### ISSUE TITLE
Angular example has tests that fail silently

### ISSUE THREAD

**Issue by alschmiedt** [rachel-fenichel/blockly-samples#1030]
**Category**
Examples

**Component**
blockly-angular

**Describe the bug**
When running the angular tests they error our with the output:
```
UnhandledRejection: Cannot read property 'range' of undefined
TypeError: Cannot read property 'range' of undefined
```

**To Reproduce**
1. Go to the blockly-angular examples repository
2. `npm run test`
3. Notice all the errors

**Expected behavior**
They should pass and we should probably report any errors on CI. It would be nice to know if everything is broken using these tests instead of having to manually test when doing dependabot updates.

**Screenshots**

**Additional context**
Looks like it has something to do with the version of node and possibly the version of angular-cli. Here is the [corresponding issue](https://github.com/karma-runner/karma/issues/3588).

**Comment by maribethb** [comment]
Example directory can be tested all at once if you run `npm run test` from `/examples` directory. If you run it from root then lerna is configured to only look at plugins, which I think is a good default behavior. It would be cool if we could get the examples tests to run only on a certain trigger (like manually triggering it if relevant) because I think it would add a ton of noise to run them for every PR
