### ISSUE TITLE
Version problem or my fault?

### ISSUE THREAD

**Issue by gsteknktaktoru** [rachel-fenichel/blockly-samples#1079]
"https://github.com/google/blockly-samples/blob/master/examples/" the examples here did not work in the new version of Blockly. I couldn't even run it in the previous version. I couldn't find the reason. There is a problem with the writing of the blocks.

When I try the same example with "blockly 5.20210325.0" the problem goes away

I tried the "Generator demo" example in old and new versions. I am sharing the results I got in both versions as pictures.
![image](https://user-images.githubusercontent.com/102715775/161435955-7eccaea2-ed76-48d2-a2e8-25ddc853fb33.png)
![2022-04-03 18 40 33](https://user-images.githubusercontent.com/102715775/161435980-80954fcf-de54-406b-97a5-c631b3626c73.png)

**Comment by alschmiedt** [comment]
Hello! Thank you for the bug, I believe this is fixed by https://github.com/google/blockly/pull/6060. If you would like to test, [8.0.1-beta.0](https://www.npmjs.com/package/blockly/v/8.0.1-beta.0) contains the fix. We are planning on releasing a patch later this week or early next week after some more testing. 

I am going to close this for now since I believe it has already been fixed, but if that is incorrect feel free to reopen it!
