### ISSUE TITLE
How do you make HTML elements draggable?

### ISSUE THREAD

**Issue by RixInGithub** [rachel-fenichel/blockly-samples#1114]
Hello, coding guys,

I am struggling with the question in the title, "how do you make HTML elements draggable?". Like, I inspected trough the workspace, no answer, only a SVG element, with text.

**Comment by maribethb** [comment]
Hello,

Can you clarify your question a bit? Is this a specific question about a problem related to Blockly you are trying to solve? 

It sounds like this is a more general question about web development. If so, then unfortunately this is not the best place to get answers. You can probably get a better explained answer by going to a place for asking general web development questions (like Stack Overflow or another forum) instead of this repository which is focused on Blockly specifically. However, if you would like to learn more about how Blockly works under the hood, you can dig into our code in the workspace_dragger.js, block_dragger.js, block_drag_surface.js files. But this is a quite complex demonstration of dragging elements so I'm not sure it's the best place to look for a general answer of how to make HTML elements draggable.

If I have misunderstood your question then please reopen this issue and add more detail so someone can better assist. Thanks!

**Comment by RixInGithub** [comment]
But Blockly blocks are draggable, right?
