### ISSUE TITLE
cross-tab-copy-paste can copy a block from inside the bubble to outside the bubble.

### ISSUE THREAD

**Issue by Taikono-Himazin** [rachel-fenichel/blockly-samples#1169]
cross-tab-copy-paste can copy a block from inside the bubble to outside the bubble.
![image](https://user-images.githubusercontent.com/25480502/174737129-091c5f20-d5de-48a2-b613-5ab8050ff116.png)

![image](https://user-images.githubusercontent.com/25480502/174737791-3524a3e3-7fe0-4e23-a06d-2d41f1c37ba2.png)

This will cause an error when generating the code.
Right-clicking is prohibited in the bubble, but you can copy using the shortcut key.

**Comment by BeksOmega** [comment]
Fixing this issue has a few steps:

1) Reproduce the issue using the steps outlined in the "To Reproduce" section. Once you can reproduce the bad behavior, you can test if your changes fixed it.
2) Modify the code in plugins/cross-tab-copy-paste/src/index.js so that the precondition function of the copy shortcut returns false if the block [is in a mutator workspace](https://developers.google.com/blockly/reference/js/Blockly.Block#isInMutator).
3) Run the reproduction steps again, and verify that the blocks cannot be copied from inside the mutator to outside of the mutator.
4) Open your PR and resolve any PR comments.

After your PR is accepted, a Blockly team member will have to publish the GitHub Pages site, and then you'll be able to see your change live!

**Comment by debaraj-barua** [comment]
Is this task still open? If so, can I pick this up?

**Comment by alschmiedt** [comment]
Yup! @debaraj-barua I just assigned you : )

**Comment by Taikono-Himazin** [comment]
@debaraj-barua 
 Thanks for the fix!
I can't wait for the release of this.
