### ISSUE TITLE
Slider field doesn't immediately resize to fit contents (Zelos)

### ISSUE THREAD

**Issue by TodePond** [rachel-fenichel/blockly-samples#1177]
**Category**
Plugins

**Component**
field-slider

**Describe the bug**
When using the Zelos theme: When you drag the slider to a number with a different number of digits (eg: slide from 99 to 100), then the size of the field doesn't update until you continue dragging, or click off of the field.

**To Reproduce**
1. Go to: https://google.github.io/blockly-samples/plugins/field-slider/test/index#renderer=zelos
2. Drag a `parent ( 50 )` block into the workspace.
3. Drag the number 50 up to 100.
4. See error:
![image](https://user-images.githubusercontent.com/15892272/176161861-22f1654f-02eb-4d53-8f10-44ad914a2882.png)

**Expected behavior**
The field should immediately resize to fit the new size of the number, like this:
![image](https://user-images.githubusercontent.com/15892272/176161998-423db9a3-f07b-4838-89b3-9c525514bca6.png)

**Screenshots**
![slider](https://user-images.githubusercontent.com/15892272/176162132-d02d0285-707d-452d-aabc-02c5dc4a0839.gif)

**Comment by maribethb** [comment]
To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

To solve this bug,
1. Run `npm run start` in the field-slider plugin to start the plugin. Then follow the reproduction steps above to be sure you can reproduce the bug.
2. In the field slider code, we need to call `this.resizeEditor()` whenever the slider value is changed. We already have an event listener for when the slider is changed, called `onSliderChange_` so you can add that line to that event listener. To understand why this is needed, you can check out the (grand)parent class of this field, [FieldTextInput](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/field_textinput.js#L485). The text input field already calls `resizeEditor` whenever the html input changes, and we need to do the same when the value changes due to the slider as well. You can see the existing call in action by typing `100` in the text input box on the field instead of using the slider, and see how it resizes correctly.
3. Try the reproduction steps again to be sure you've fixed the bug.
4. Follow the rest of the steps to verify your change and open a PR as described in the Contributing docs.

**Comment by MashaZyryanova** [comment]
I can help with this one

**Comment by TodePond** [comment]
Amazing! Thanks very much :)
