### ISSUE TITLE
Can't tell which blockly versions the plugins are compatible with?

### ISSUE THREAD

**Issue by mrkprdo** [rachel-fenichel/blockly-samples#1353]
**Category**
Plugins

**Component**
All / cross-tab-copy-paste

**Describe the bug**
Can't really tell which blockly version the plugins may or can work.

**To Reproduce**
n/a

**Expected behavior**
The blockly plugin npm will require a certain version to work.

**Screenshots**

**Additional context**

**Comment by maribethb** [comment]
Hello, you can tell from the plugin's [package.json](https://github.com/google/blockly-samples/blob/master/plugins/cross-tab-copy-paste/package.json) file in the peerDependencies section. Also if you install the package and you don't have a compatible version npm should alert you. 

Is there another place you'd expect to see this information / do you have any suggestions about where to surface it?

In general we only test plugins with the latest major version of blockly, so currently v9. They may work with previous versions but we don't guarantee it so that's why we bump the peer dependency of the plugins when we do a new major version of Blockly. In that case, the plugin itself also gets a new major version bump so that you won't be automatically upgraded to an incompatible version. So if you need to use Blockly v8 you can try going back to the previous major version of the plugin as well, though keep in mind you'll be missing out on bug fixes until you update.

Hope that helps!
