### ISSUE TITLE
Localization broken in field-date

### ISSUE THREAD

**Issue by frck006** [rachel-fenichel/blockly-samples#1530]
It's more a question than a bug.
I would like to know how to change the local in @blockly/field-date ?

When I set '**fr**', this change "today" but not the month.
![image](https://user-images.githubusercontent.com/10244725/214940618-79441b81-0dda-44ad-a9c3-e42179a13bf9.png)

Thanks

**Comment by cpcallen** [comment]
I am pretty sure this is actually a bug.

You don't describe how your code changes the locale, but I added

```JS
import * as Fr from 'blockly/msg/fr';
Blockly.setLocale(Fr);
```
to the top of `plugins/field-date/test/index.js` (just beneath `import * as Blockly…`), and was able to reproduce exactly.

I believe the problem is in [`FieldDate.loadLanguage_`](https://github.com/google/blockly-samples/blob/e0d85d4044baa04773fbca8710f3354dc8b83b08/plugins/field-date/src/field_date.js#L74):
```JS
  static loadLanguage_() {
    for (const prop in goog.i18n) {
      if (prop.startsWith('DateTimeSymbols_')) {
        const lang = prop.substr(16).toLowerCase().replace('_', '.');
        // E.g. 'DateTimeSymbols_pt_BR' -> 'pt.br'
        if (goog.getObjectByName(lang, Blockly.Msg)) {
          goog.i18n.DateTimeSymbols = goog.i18n[prop];
          break;
        }
      }
    }
  }
```
As far as I can tell this is expecting to find a property named `Blockly.Msg.fr`(or whatever language has been set) and no such property exists so `goog.i18n.DateTimeSymbols` is never set.

I'm not really sure how this could ever have worked.  Did `Blockly.Msg` formerly have a property named for the language loaded?

**Comment by alicialics** [comment]
Looks like the snippet above (ie `loadLanguage_()` was removed in https://github.com/google/blockly-samples/pull/1705
Instead of `goog.ui.DatePicker()` it was replaced with browser's native date picker.  However it does mean that the strings won't be localized if the browser locale != Blockly locale.

cc @BeksOmega

**Comment by rachel-fenichel** [comment]
Is there a way to force the native date picker to use a specific locale by code other than the browser locale?

**Comment by rachel-fenichel** [comment]
It looks like we don't have a way to force the locale of the date picker. However, if there's a mismatch between Blockly locale and browser locale there's a good chance that the browser locale is the user's actual preferred locale, and that they will understand the month strings that are available. This seems acceptable, given that it allows us to not implement a custom date picker (or import one from elsewhere, as we did with the Closure UI library).
