### ISSUE TITLE
Blockly-Flutter

### ISSUE THREAD

**Issue by beyonlo** [rachel-fenichel/blockly-samples#1543]
Hi all.

Thank you for this amazing project!

**Category**

 - Examples

**Component**

**Blockly-Flutter**

I would like to add Blockly to a Flutter App. For now, if Blockly works with Flutter build to web is fine, but I would like to use Blockly integrated also for specific platforms, IOS, Android, Windows, Linux and MACOS. As Flutter build for those all platforms, would be great to use Blockly together. Is possible? 

Thank you!

**Comment by gonfunko** [comment]
I'm not deeply familiar with Flutter, but it seems like it provides a webview component. You should be able to load Blockly into that on non-web platforms. I'm going to close this issue, but if you have followup questions feel free to ask in the [forum](https://groups.google.com/forum/#!forum/blockly), since other users may have more experience with Flutter and be able to help there as well.
