### ISSUE TITLE
Import Plugin Source code into project

### ISSUE THREAD

**Issue by GogittossjX** [rachel-fenichel/blockly-samples#1631]
**Category**
Plugins

**Describe the bug**

Hello, I am working on a project and where i need to ship a blockly application to various computers. My current solution is to have blockly's source code included in the project and this has been working so far. Im working off on of the demos an to include blockly, i do this <script src="blocks_compressed.js"></script>. Now i am trying to include the continous toolbox plugin to the project by downloading the source code and including it into the project, but am having no luck. I copied the files into the blockly folder and tried the import statement from the readme but i get the error "import declarations may only appear at top level of a module" and the same thing when i try to include it into the html like so <script src="../continuous-toolbox/src/index.js"></script>. So how am i supposed to properly install it?

Thank you

**Comment by BeksOmega** [comment]
Hello! Thank you for your question :D

We do not generally recommend using the blockly source code directly. Instead we recommend acquiring it from npm or unpkg, as outlined in our docs: https://developers.google.com/blockly/guides/get-started/web#get_the_code

Similarly for the plugin, instead of loading the sources directly you can [load it from npm](https://www.npmjs.com/package/@blockly/continuous-toolbox) (as recommended) or unpkg:
```
  <script src="https://unpkg.com/@blockly/continuous-toolbox@3.0.11/dist/index.js"></script>
```

If you want to download the actual source code for the plugin, you'd need to have webpack installed (and other related tooling) to be able to build it and then import it, which is a major hastle. If you acquire it from npm or unpkg instead, it's a much simpler more streamlined process =)

I hope that helps! If you have any further questions please direct them to our [developer forum](https://groups.google.com/g/blockly) =)
--Beka
