### ISSUE TITLE
typo in getting started codelab

### ISSUE THREAD

**Issue by bullyDD** [rachel-fenichel/blockly-samples#1648]
Hi everyone,

I was doing this tutorial and i found out there is a synthaxical error on this[ codelab page](https://blocklycodelabs.dev/codelabs/getting-started/index.html#3) . 

In the first section 

> 4. Add Blockly libraries

The author wrote 

> Blockly releases are published on npm on a quarterly basis. For this codelab you will import blockly using **_unkpg_**

Instead of **unpkg**.

I hope this is helpful.

Kind

BullyDD

**Comment by maribethb** [comment]
Hello, thank you for the issue. 

This is a good issue for someone who is new to GitHub and would like to contribute to blockly. You can find details about contributing to blockly [here](https://developers.google.com/blockly/guides/contribute/samples), and the source for the codelabs is located [here](https://github.com/google/blockly-samples/tree/master/codelabs/getting_started). This issue can be fixed by correcting the typo in the `getting_started.md` file and opening a PR.

**Comment by maribethb** [comment]
closed by #1656
