### ISSUE TITLE
Disable lint as a required check before merging PRs

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1699]
It's configured here: https://github.com/google/blockly-samples/blob/master/.github/workflows/build.yml#L37

Linting in blockly-samples is [misconfigured in a complicated way](https://github.com/google/blockly-samples/issues/1695). Linting has blocked several PRs. Neil proposed turning off the lint requirement and periodically running it to find and fix actual problems. The team agreed.

Maribeth agreed as long as we have a plan for eventually turning lint back on. This may include easing up on some of the lint rules.

**Comment by maribethb** [comment]
We talked about this as a group and decided that we'd leave the github action on. It's not a required check so you can merge PRs even if linting fails, and anyone should feel free to do so if they find themselves blocked by linting configuration problems.

I'll note that you are most likely to run into problems when moving code from core into samples. In the more typical case of working on an existing plugin, lint should continue to work as normal and ideally lint problems can be fixed before they're committed, which is why we decided to leave the check running without being blocking.
