### ISSUE TITLE
The DropDownDiv was off the right position of field-bitmap

### ISSUE THREAD

**Issue by AdwardWong** [rachel-fenichel/blockly-samples#1720]
**Category**
 - Plugins

**Component**

 The name of the component that has a bug (@blockly/field-bitmap Demo). 

**Describe the bug**

when add more than one field, then the DropDownDiv was off the right position.

**To Reproduce**

1. npm install @blockly/field-bitmap --save
2. the init block code as below:
```
 Blockly.Blocks["Nixie_tube"] = {
  init: function () {
    this.appendDummyInput()
      .appendField("D1: ")
      .appendField(new FieldBitmap(), "D1")
    this.appendDummyInput()
      .appendField("D2: ")
      .appendField(new FieldBitmap(), "D2")
    this.appendDummyInput()
      .appendField("D3: ")
      .appendField(new FieldBitmap(), "D3");
    this.setInputsInline(true);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
  }
};

```
3. Click on D3 field to open DropDownDiv. 
4. See error "DropDownDiv" was off the right position.

**Expected behavior**
Fix this bug ASAP

**Screenshots**
<img width="577" alt="bitmap_bug" src="https://github.com/google/blockly-samples/assets/13374858/136a1f24-2d0b-45c3-bf60-5b8e2d7ac14c">

**Comment by itsjayway** [comment]
good afternoon, I was able to recreate the error on my end. I'll try and put up a PR within the week for maintainers' review
![image](https://github.com/google/blockly-samples/assets/70596906/841b6920-a211-401a-9a40-ad0f56890a08)

**Comment by AdwardWong** [comment]
>    Thank you ,  Looking forward to your good news.

**Comment by itsjayway** [comment]
good afternoon @AdwardWong,
unfortunately, I don't think I can arrive at a solution at this time. I will paste my `plugins/field-bitmap/test/index.js` below so that someone may replicate.

if a maintainer is able to provide a starting point, I'd greatly appreciate it; I'm going to try some changes out of [blockly](https://github.com/google/blockly ) directly, as I would guess it's a problem with `getContentDiv()` and chained fields - [file](https://github.com/google/blockly/blob/develop/core/dropdowndiv.ts)

https://gist.github.com/jibranabsarulislam/c20d9a636b7fc49b9672d2938e64ad36

**Comment by AdwardWong** [comment]
> jibranabsarulislam
Thank you, as you said, this could be a blockly source code issue.
