### ISSUE TITLE
shadow-block-converter should use `setShadowState` instead of `setShadow`

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2064]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

shadow-block-converter

### Description

Currently the shadow-block-converter plugin uses `setShadow` on a block to swap it between being a shadow and being a real block. Instead it should use `setShadowState` or kill/create the real block.

`setShadow` is not a supported method of creating shadow blocks, because serialization looks at the connection's shadow state, not the state of a connected shadow block.

### Reproduction steps

1. 
2. 
3.

**Comment by maribethb** [comment]
@johnnesky did you want to follow up on this?

**Comment by johnnesky** [comment]
Taking a look!

Aside from API usage, the current behavior of the plugin is correct. An edited shadow block gets converted to a regular block, and both the regular block and the original shadow block can be serialized successfully and recovered after reloading. You can recover the original shadow block either by undoing (caveat: https://github.com/google/blockly/issues/6456) or by removing the regular block.

However the plugin uses the `setShadow()` method of `Block`, which is marked as internal and unsupported because it can apparently cause confusion depending on how it's used. In principle, a `Connection` is intended to own the shadow status of its child block, and using a method of the child block to toggle its own shadow status violates that intention. In many cases it appears to work as expected anyway, including in this plugin, but there are corner cases where it does not work as expected.

The main feature of a shadow block is that it gets "stashed" when a regular block is attached to the same connection, and reappears when the regular block is removed. A `Connection` keeps a member variable called `shadowState` to record this stashed shadow block while the regular block is attached, but calling `setShadow()` on the child block does not update the associated `Connection`'s `shadowState`... at least, not directly, and in some ways it doesn't have to. `Connection`'s public method `getShadowState(returnCurrent?: boolean)` returns the `Connection`'s shadow state, but depending on the argument and context it has two possible values it can return: its internal `shadowState`, or the newly serialized state of any currently connected shadow child. If the argument is true and there exists a shadow child, that child's state will be returned. The relevant places where `getShadowState(...)` is called pass true, and thus a shadow child could be considered to take precedence over the internal shadow state. For example, if `setShadow(true)` is called on a child, then the next time the parent `Connection` is serialized the child will be serialized like any other shadow block. Also, if a regular block is attached to the same `Connection` as the shadow block, then the process of connecting the regular block will record the `shadowState` based on the shadow block, and if the regular block is removed then the shadow block will return. So far, so good!

However, if `setShadow()` is called repeatedly to toggle a block's shadow status back and forth, one might expect previous versions of the block to be saved to the parent `Connection`'s internal `shadowState`, or at least for the system to behave as if this were the case, but it does not. That's actually kinda nice for this plugin, because it means that the original `shadowState` remains as a permanent default value that returns if you ever remove an edited value. However, standard Blockly behavior is that the latest edits to shadow blocks are retained in `shadowState`, and the `setShadow()` method can violate this expectation.

Updating this plugin to stop using `setShadow()` will be tricky, because there does not exist any other API to convert a shadow block to a regular block. We could add one, but that would be basically reimplementing this plugin as part of Blockly core. (which is an approach I still think merits consideration!) Beka has suggested working around it by serializing the recently edited shadow block to JSON, then reinstantiating the JSON as a regular block and attaching this clone to the parent Connection in place of the shadow block. This is messy but can probably work?

I would like to preserve the feature of this plugin that the original `shadowState` is retained as a permanent default value. The plan to attach a new regular block to the parent `Connection` will trigger the behavior of overwriting the `Connection`'s internal `shadowState` with the previously connected shadow block's state, which is a problem because the plugin works by listening for change events that are broadcast after the shadow block has been edited and no longer has original state that I want to preserve. Fortunately, the plugin can call `getShadowState()` prior to attaching a regular block version of the block, passing false to access the original saved `shadowState` which shouldn't have been updated yet, and then after attaching the regular version of the block, the plugin can call `setShadowState()`, providing the state that we previously accessed in order to retain it again in the `Connection`.

All this will be even more complicated by the fact that the plugin supports nested shadow blocks... I'll give it a shot and we can review my attempt to decide if we like this plan.
