### ISSUE TITLE
Disabled blocks transparent in downloaded screenshots

### ISSUE THREAD

**Issue by laurensvalk** [rachel-fenichel/blockly-samples#2157]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

dev-tools/screenshot

### Description

Downloaded screenshots render disabled blocks as transparent, which makes them hard to see.

Expected result: Downloaded file looking the same, with the same grid-like block background as visible in the browser.

### Reproduction steps

![image](https://github.com/google/blockly-samples/assets/12326241/7b538671-1b8e-4264-8c03-511656b91e3d)

-----

Following the steps on the [advanced playground](https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html#debugEnabled=false) above produces:

-----

![screenshot (3)](https://github.com/google/blockly-samples/assets/12326241/634a8a8d-6381-46be-94d6-56bfdc3abc8a)

**Comment by rachel-fenichel** [comment]
Thanks for the report. We'd happily take a patch for this one.

The code is in [screenshot.js](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/screenshot.js) and I suspect that the problem is that there's a filter defined at the top level of the SVG that is applied to the disabled block but is somehow missed in the export.
