### ISSUE TITLE
Scroll options extends undefined class

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2354]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

scroll-options

### Description

See title.

### Reproduction steps

1. Load the plugin test page with the latest beta linked.

### Stack trace

```shell
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at eval (ScrollBlockDragger.js:71:41)
    at ./src/ScrollBlockDragger.js (test_bundle.js:1891:1)
    at __webpack_require__ (test_bundle.js:2327:42)
    at eval (index.js:9:77)
    at ./src/index.js (test_bundle.js:1913:1)
    at __webpack_require__ (test_bundle.js:2327:42)
    at eval (index.js:4:68)
    at ./test/index.js (test_bundle.js:1935:1)
    at __webpack_require__ (test_bundle.js:2327:42)
    at test_bundle.js:2403:37
```

**Comment by maribethb** [comment]
This plugin was updated to work with the v11 dragging system at some point, but then additional changes were made in core and this wasn't updated. It has a couple of problems:

- In core, `Blockly.Dragger` is now exported under `Blockly.dragging.Dragger` which just needs to be updated in 2 places. easy fix
- The plugin calls `draggable.moveDuringDrag`. `moveDuringDrag` is not part of the `Draggable` interface so there is no guarantee that it exists. It does exist for things we currently expect to drag, i.e. blocks and workspace comments. it may not exist for custom draggables but these methods will still attempt to be called. also `moveDuringDrag` is marked `@internal` on `BlockSvg`
- The plugin calls `draggable.getBoundingRectangle()` -- same exact caveats apply here.

Since this plugin isn't written in typescript, it compiles and runs fine. however, if someone did create a custom draggable (not sure if this is actually possible) it would probably crash when trying to drag that custom thing. edit: it does throw errors when you try to drag bubbles since they don't have those two methods.
