### ISSUE TITLE
toolbox_search plugin support blockly 9.2.1 version

### ISSUE THREAD

**Issue by mlzboy** [rachel-fenichel/blockly-samples#2451]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

I checked the repo It seems toolbox_search plugin is publish since blockly 10,didn't support xml toolbox configuration,could it back support xml configuration way and support 9 version

**Comment by cpcallen** [comment]
Unfortunately we do not have the resources to add additional support for XML to plugins in order to support older versions of Blockly.  We recommend you update to a newer version of Blockly—preferably v11—because then you can use all the plugins and benefit from the many bugfixes we have made in the meantime.
